from django.urls import path
from .views import (
    StartDraftOrderView,
    AddLineView,
    UpdateLineQuantityView,
    RemoveLineView,
    SetDeliveryDetailsView,
    SetPaymentTypeView,
    ApplyCouponView,
    ConfirmOrderView,
    CancelOrderView,
    AdvanceStateView,
    OrderListView,
    AllOrdersView,
    AppliedCouponListView,
    OrderDetailView,
    UpdateOrderStatusView,
    PaymentLinkView,
    CancelSupersededCheckoutView,
    MercadoPagoWebhookView,
    CurrentDraftView,
    LatestActiveOrderView,
    SetPickupView,
    OrderSummaryView,
    SetClientView,
)

urlpatterns = [
    path('', OrderListView.as_view(), name='order-list'),
    path('all/', AllOrdersView.as_view(), name='order-all'),
    path('applied-coupons/', AppliedCouponListView.as_view(), name='order-applied-coupons'),
    path('draft/', StartDraftOrderView.as_view(), name='start-draft-order'),
    path('draft/current/', CurrentDraftView.as_view(), name='current-draft'),
    path('latest-active/', LatestActiveOrderView.as_view(), name='latest-active-order'),
    path('payments/mercadopago/webhook/', MercadoPagoWebhookView.as_view(), name='mercadopago-webhook'),
    path('<uuid:order_id>/', OrderDetailView.as_view(), name='order-detail'),
    path('<uuid:order_id>/payment-link/', PaymentLinkView.as_view(), name='create-payment-link'),
    path(
        'payments/attempts/<uuid:payment_attempt_id>/cancel/',
        CancelSupersededCheckoutView.as_view(),
        name='cancel-payment-checkout',
    ),
    path('<uuid:order_id>/status/', UpdateOrderStatusView.as_view(), name='order-status'),
    path('<uuid:order_id>/lines/', AddLineView.as_view(), name='add-line'),
    path('<uuid:order_id>/lines/<uuid:line_id>/', UpdateLineQuantityView.as_view(), name='update-line-quantity'),
    path('<uuid:order_id>/lines/<uuid:line_id>/remove/', RemoveLineView.as_view(), name='remove-line'),
    path('<uuid:order_id>/delivery/', SetDeliveryDetailsView.as_view(), name='set-delivery-details'),
    path('<uuid:order_id>/pickup/', SetPickupView.as_view(), name='set-pickup'),
    path('<uuid:order_id>/client/', SetClientView.as_view(), name='set-client'),
    path('<uuid:order_id>/summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('<uuid:order_id>/payment-type/', SetPaymentTypeView.as_view(), name='set-payment-type'),
    path('<uuid:order_id>/coupon/', ApplyCouponView.as_view(), name='apply-coupon'),
    path('<uuid:order_id>/confirm/', ConfirmOrderView.as_view(), name='confirm-order'),
    path('<uuid:order_id>/cancel/', CancelOrderView.as_view(), name='cancel-order'),
    path('<uuid:order_id>/advance/', AdvanceStateView.as_view(), name='advance-state'),
]
