from typing import Protocol
from modules.client.domain.models.address import Address


class AddressRepositoryPort(Protocol):
    def save(self, address: Address) -> None: ...
    def find_by_id(self, address_id: str) -> Address | None: ...
    def find_by_client_id(self, client_id: str) -> list[Address]: ...
    def update(self, address: Address) -> None: ...
    def delete(self, address_id: str) -> None: ...
    def unset_default_for_client(self, client_id: str) -> None: ...
