from typing import Protocol
from modules.client.domain.models.client import Client


class ClientRepositoryPort(Protocol):
    def save(self, client: Client) -> None: ...
    def find_by_id(self, client_id: str) -> Client | None: ...
    def find_by_phone(self, phone_number: str) -> Client | None: ...
    def update(self, client: Client) -> None: ...
