"""Bootstrap staff members: create the Supabase Auth user + the staff row.

Django discovers management commands at ``<app>/management/commands/`` (top
level of the app package), so the CLI entry lives here instead of inside the
hexagonal infrastructure tree.

Usage:
    uv run python manage.py create_staff --email caja@rapidfood.local --name "Caja Uno" --role CASHIER
"""
from __future__ import annotations

import secrets
import string

import requests
from django.core.management.base import BaseCommand, CommandError

from modules.staff.domain.models.staff_user import StaffRole
from shared.infrastructure.auth.settings import SupabaseAuthSettings
from shared.infrastructure.prisma.db import db


class Command(BaseCommand):
    help = "Create a Supabase Auth user and the matching staff row (ADMIN/CASHIER/KITCHEN)."

    def add_arguments(self, parser) -> None:
        parser.add_argument("--email", required=True, help="Staff login email")
        parser.add_argument("--name", required=True, help="Staff display name")
        parser.add_argument(
            "--role",
            required=True,
            choices=[r.value for r in StaffRole],
            help="Staff role: ADMIN, CASHIER or KITCHEN",
        )
        parser.add_argument(
            "--password",
            default=None,
            help="Initial password (default: a random one, printed once)",
        )

    def handle(self, *args, **options) -> None:
        settings = SupabaseAuthSettings.from_env()
        if not settings.service_role_key:
            raise CommandError(
                "SUPABASE_SERVICE_ROLE_KEY is not set; the admin API cannot create users. "
                "Set it in .env or create the user manually in the Supabase dashboard."
            )

        password = options["password"] or self._random_password()
        role = StaffRole(options["role"])
        email = options["email"]

        user = self._create_supabase_user(
            settings=settings,
            email=email,
            password=password,
        )
        self._create_staff_row(
            supabase_auth_id=str(user["id"]),
            email=email,
            name=options["name"],
            role=role,
        )

        self.stdout.write(self.style.SUCCESS(f"Staff '{email}' created with role {role.value}."))
        if not options["password"]:
            self.stdout.write(
                self.style.WARNING(f"Autogenerated password (shown once): {password}")
            )

    def _create_supabase_user(self, settings, email: str, password: str) -> dict:
        url = f"{settings.url.rstrip('/')}/auth/v1/admin/users"
        response = requests.post(
            url,
            json={
                "email": email,
                "password": password,
                "email_confirm": True,
            },
            headers={
                "apikey": settings.service_role_key,
                "Authorization": f"Bearer {settings.service_role_key}",
                "Content-Type": "application/json",
            },
            timeout=20,
        )
        if response.status_code not in (200, 201):
            raise CommandError(
                f"Supabase admin API rejected user creation (HTTP {response.status_code}): "
                f"{response.text[:300]}"
            )
        payload = response.json()
        if "id" not in payload:
            raise CommandError(f"Unexpected Supabase response: {str(payload)[:200]}")
        return payload

    def _create_staff_row(
        self,
        supabase_auth_id: str,
        email: str,
        name: str,
        role: StaffRole,
    ) -> None:
        try:
            db.client.staff.create(
                data={
                    "supabaseAuthId": supabase_auth_id,
                    "email": email,
                    "name": name,
                    "role": role.value,
                }
            )
        except Exception as exc:  # duplicate email/missing DB
            raise CommandError(
                f"Supabase user was created but the staff row failed: {exc}"
            ) from exc

    @staticmethod
    def _random_password(length: int = 16) -> str:
        alphabet = string.ascii_letters + string.digits
        return "".join(secrets.choice(alphabet) for _ in range(length))