-- AlterTable
-- NOTE: this migration previously added `is_active` and `min_order_amount` to
-- "coupon", but BOTH columns were already added by
-- 20260821012555_add_delivery_module. Keeping the duplicates here breaks
-- `prisma migrate deploy` from a clean DB, so this migration is now a no-op.