from __future__ import annotations

from modules.business.application.ports.driven.business_repository_port import (
    BusinessConfigurationRepositoryPort,
)
from modules.business.application.ports.driver.upsert_business_hours_port import (
    UpsertBusinessHoursCommand,
)
from modules.business.domain.errors.business_errors import (
    InvalidBusinessHoursError,
)
from modules.business.domain.models.business_configuration import BusinessHours

_VALID_WEEKDAYS = {
    "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY",
    "FRIDAY", "SATURDAY", "SUNDAY",
}

def _validate_time(value: str) -> None:
    """Validate HH:MM format."""
    parts = value.split(":")
    if len(parts) != 2:
        raise InvalidBusinessHoursError(f"Invalid time format: '{value}'. Expected HH:MM.")
    try:
        h, m = int(parts[0]), int(parts[1])
        if not (0 <= h <= 23 and 0 <= m <= 59):
            raise ValueError
    except ValueError:
        raise InvalidBusinessHoursError(f"Invalid time: '{value}'.")


class UpsertBusinessHoursUseCase:
    def __init__(self, repo: BusinessConfigurationRepositoryPort) -> None:
        self._repo = repo

    def execute(self, command: UpsertBusinessHoursCommand) -> None:
        # Validate
        seen_days: set[str] = set()
        for h in command.hours:
            if h.open_week_day not in _VALID_WEEKDAYS:
                raise InvalidBusinessHoursError(
                    f"Invalid weekday: '{h.open_week_day}'"
                )
            if h.open_week_day in seen_days:
                raise InvalidBusinessHoursError(
                    f"Duplicate weekday entry: '{h.open_week_day}'"
                )
            seen_days.add(h.open_week_day)
            _validate_time(h.open_from_hour)
            _validate_time(h.open_to_hour)

        hours_domain = [
            BusinessHours(
                id="",  # will be generated by DB
                openWeekDay=h.open_week_day,
                openFromHour=h.open_from_hour,
                openToHour=h.open_to_hour,
                businessConfigId=command.business_config_id,
            )
            for h in command.hours
        ]
        self._repo.replace_business_hours(command.business_config_id, hours_domain)
