from typing import Optional, List, Protocol
from modules.catalog.domain.models.ingredient import Ingredient

class IngredientRepositoryPort(Protocol):
    def save(self, ingredient: Ingredient) -> Ingredient: ...
    def find_by_id(self, ingredient_id: str) -> Optional[Ingredient]: ...
    def list_all(self) -> List[Ingredient]: ...
