from typing import Optional, List, Protocol
from modules.catalog.domain.models.modifier_group import ModifierGroup
from modules.catalog.domain.models.modifier_option import ModifierOption

class ModifierRepositoryPort(Protocol):
    def save_group(self, group: ModifierGroup) -> ModifierGroup: ...
    def find_group_by_id(self, group_id: str) -> Optional[ModifierGroup]: ...
    def list_groups_for_product(self, product_id: str) -> List[ModifierGroup]: ...
    def delete_group(self, group_id: str) -> None: ...
    def save_option(self, option: ModifierOption) -> ModifierOption: ...
    def find_option_by_id(self, option_id: str) -> Optional[ModifierOption]: ...
    def list_options_for_group(self, group_id: str) -> List[ModifierOption]: ...
    def delete_option(self, option_id: str) -> None: ...
