from typing import Optional, List, Protocol
from modules.catalog.domain.models.product_variant import ProductVariant

class VariantRepositoryPort(Protocol):
    def save(self, variant: ProductVariant) -> ProductVariant: ...
    def find_by_id(self, variant_id: str) -> Optional[ProductVariant]: ...
    def list_for_product(self, product_id: str) -> List[ProductVariant]: ...
    def delete(self, variant_id: str) -> None: ...
